"""initial schema

Revision ID: bb5d42326993
Revises: 
Create Date: 2026-06-26 20:09:17.566324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb5d42326993'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_entries',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('process_definitions',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('template_definitions',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('owner_key', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('module_definitions',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('process_def_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('intro', sa.JSON(), nullable=True),
    sa.Column('responsible_role', sa.String(length=128), nullable=True),
    sa.Column('estimated_effort', sa.String(length=128), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('unlock_rule', sa.JSON(), nullable=True),
    sa.Column('ai_knowledge_config', sa.JSON(), nullable=True),
    sa.Column('output_schema_key', sa.String(length=128), nullable=True),
    sa.Column('target_mappings', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['process_def_id'], ['process_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('process_instances',
    sa.Column('process_def_id', sa.String(length=36), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_org', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['process_def_id'], ['process_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('module_instances',
    sa.Column('process_instance_id', sa.String(length=36), nullable=False),
    sa.Column('module_def_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('unlocked', sa.Boolean(), nullable=False),
    sa.Column('assigned_role', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['module_def_id'], ['module_definitions.id'], ),
    sa.ForeignKeyConstraint(['process_instance_id'], ['process_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('step_definitions',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('module_def_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('ai_knowledge_config', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['module_def_id'], ['module_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canonical_outputs',
    sa.Column('module_instance_id', sa.String(length=36), nullable=False),
    sa.Column('schema_key', sa.String(length=128), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['module_instance_id'], ['module_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_jobs',
    sa.Column('module_instance_id', sa.String(length=36), nullable=False),
    sa.Column('target_system', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('mapped_payload', sa.JSON(), nullable=True),
    sa.Column('preview', sa.JSON(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['module_instance_id'], ['module_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_definitions',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('step_def_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('ai_help_enabled', sa.Boolean(), nullable=False),
    sa.Column('validation_rules', sa.JSON(), nullable=True),
    sa.Column('knowledge_scope', sa.JSON(), nullable=True),
    sa.Column('visibility_rule', sa.JSON(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['step_def_id'], ['step_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_tasks',
    sa.Column('module_instance_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reviewer', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['module_instance_id'], ['module_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('step_instances',
    sa.Column('module_instance_id', sa.String(length=36), nullable=False),
    sa.Column('step_def_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['module_instance_id'], ['module_instances.id'], ),
    sa.ForeignKeyConstraint(['step_def_id'], ['step_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_validation_results',
    sa.Column('step_instance_id', sa.String(length=36), nullable=False),
    sa.Column('question_def_id', sa.String(length=36), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=True),
    sa.Column('issues', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_def_id'], ['question_definitions.id'], ),
    sa.ForeignKeyConstraint(['step_instance_id'], ['step_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers',
    sa.Column('step_instance_id', sa.String(length=36), nullable=False),
    sa.Column('question_def_id', sa.String(length=36), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('ai_suggested', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_def_id'], ['question_definitions.id'], ),
    sa.ForeignKeyConstraint(['step_instance_id'], ['step_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backend_validation_results',
    sa.Column('step_instance_id', sa.String(length=36), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['step_instance_id'], ['step_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_uploads',
    sa.Column('question_def_id', sa.String(length=36), nullable=False),
    sa.Column('step_instance_id', sa.String(length=36), nullable=False),
    sa.Column('answer_id', sa.String(length=36), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['question_def_id'], ['question_definitions.id'], ),
    sa.ForeignKeyConstraint(['step_instance_id'], ['step_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_suggestions',
    sa.Column('context', sa.String(length=32), nullable=False),
    sa.Column('module_instance_id', sa.String(length=36), nullable=True),
    sa.Column('step_instance_id', sa.String(length=36), nullable=True),
    sa.Column('question_def_id', sa.String(length=36), nullable=True),
    sa.Column('suggestion_type', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('open_questions', sa.JSON(), nullable=True),
    sa.Column('source_upload_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['module_instance_id'], ['module_instances.id'], ),
    sa.ForeignKeyConstraint(['question_def_id'], ['question_definitions.id'], ),
    sa.ForeignKeyConstraint(['source_upload_id'], ['file_uploads.id'], ),
    sa.ForeignKeyConstraint(['step_instance_id'], ['step_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_suggestions')
    op.drop_table('file_uploads')
    op.drop_table('backend_validation_results')
    op.drop_table('answers')
    op.drop_table('ai_validation_results')
    op.drop_table('step_instances')
    op.drop_table('review_tasks')
    op.drop_table('question_definitions')
    op.drop_table('import_jobs')
    op.drop_table('canonical_outputs')
    op.drop_table('step_definitions')
    op.drop_table('module_instances')
    op.drop_table('process_instances')
    op.drop_table('module_definitions')
    op.drop_table('users')
    op.drop_table('template_definitions')
    op.drop_table('process_definitions')
    op.drop_table('knowledge_entries')
    # ### end Alembic commands ###
